### ISSUE TITLE
AuditlogHistoryField is not working

### ISSUE THREAD

**Issue by tushar-thantharate** [jjkester/django-auditlog#10]
AuditlogHistoryField is not working with existing model and new models.

```
class TestAudit(models.Model):
    is_approved = models.BooleanField(default=False)
    history = AuditlogHistoryField()

    def __unicode__(self):
        return '%d' % self.id
    
auditlog.register(TestAudit)
```

I can see change history in auditlog_logentry table but not able to access it using AuditlogHistoryField.

Also, in models for south migration introspection rule is written as 
```add_introspection_rules([], ["^southtut\.fields\.UpperCaseField"])``` (Django example one)

**Comment by jjkester** [comment]
I assume commit bee1f08 fixed this issue. If not, please open a new issue referencing this one.

**Comment by Paul424** [comment]
I cannot figure out how to use "AuditlogHistoryField" in the admin view. I can see it returns the correct logentries (from shell) but i like to have it integrated in the admin view of the model. So ideal would be to have an ul rendered that shows all changes made to this model instance. For me it would also be fine to just render a button/link to the logentry admin view filtered for the model instance.
Is this possible?
Paul

**Comment by jjkester** [comment]
Hi Paul,

This is not possible by just referencing the `AuditlogHistoryField`. However, it would be possible by customizing the Django Admin. Issue #68 is relevant in this case.
