### ISSUE TITLE
v4.1.2 crashes every Django < 1.11a1

### ISSUE THREAD

**Issue by audiolion** [jjkester/django-auditlog#104]
No tests leads to problems 😢 

The PR imports `from django.urls.exceptions import NoReverseMatch` from [master](https://github.com/django/django/blob/master/django/urls/exceptions.py) which [doesn't exist on Django 1.8](https://github.com/django/django/tree/1.8.17/django/urls/exceptions.py)

and causes the server to not even startup

1.8, 1.9, and 1.10 uses `from django.core.urlresolvers import NoReverseMatch` so only on [1.11a1](https://github.com/django/django/commit/16411b8400ad08f90c236bb2e18f65c655f903f8#diff-5d9ed209ff6312a66554b309734f3544) does the new code work

**Comment by jjkester** [comment]
Fixed in #105. A test is still needed though, so keeping this issue open.

**Comment by jjkester** [comment]
0.4.3 is released, fixing this nasty bug.

**Comment by audiolion** [comment]
Thank you for the quick release! Agreed we need to get test for the regression/just adding a test for the mixins.py file should do the trick

**Comment by jjkester** [comment]
I thought just to release a fix asap so everyone can get on with their job. As I accepted the PR that caused this I thought "well, a (regression) test can always be made in case something breaks". The universe seems to have decided that this needs a test right away.
