### ISSUE TITLE
AuditlogHistoryField cascade deletes log entries

### ISSUE THREAD

**Issue by texnic** [jjkester/django-auditlog#108]
auditlog history in admin looks excellent and contains the complete modification description. However, if I delete an object, the whole history for that object, except the delete action, is deleted. It looks like the database entries for intermediate changes are deleted when the object is deleted. It is possible to keep them?

**Comment by audiolion** [comment]
To combat the issue of sending notifications on delete requests I wrote the wrapper

```

class NotifyMixinBase(object):
    verb = ''
    recipient = None
    obj = None
    target = None
    target_text = None
    target_url = None

    @property
    def exception_message(self):
        raise NotImplementedError

    def notify(self):
        if self.obj is None:
            raise TypeError(self.exception_message)
        if self.recipient:
            if self.target_text and self.target_url:
                notify.send(
                    None,
                    actor=self.request.user,
                    verb=self.verb,
                    recipient_list=self.recipient,
                    target_text=self.target_text,
                    target_url=self.target_url,
                    obj=self.obj,
                    nf_type='default_bootstrap')
            elif self.target_text:
                notify.send(
                    None,
                    actor=self.request.user,
                    verb=self.verb,
                    recipient_list=self.recipient,
                    target_text=self.target_text,
                    obj=self.obj,
                    nf_type='default_bootstrap')
            else:
                notify.send(
                    None,
                    actor=self.request.user,
                    verb=self.verb,
                    recipient_list=self.recipient,
                    target=self.target,
                    obj=self.obj,
                    nf_type='default_bootstrap')


class DeleteNotifyMixin(NotifyMixinBase):
    verb = 'has deleted'
    exception_message = ("obj is None. delete(request, *args, **kwargs) method was not executed "
                         "or self.get_object() did not return saved instance. "
                         "\nSingleObjectMixin's get_object() returns the instance to be deleted.")

    def delete(self, request, *args, **kwargs):
        self.obj = self.get_object()
        if self.target_text is None:
            self.target_text = str(self.obj)
        self.notify()
        return super(DeleteNotifyMixin, self).delete(request, *args, **kwargs)
```

which assigns target_text and, from the view I will sometimes set the `target_url` too so that if the object is deleted the information is not lost.

The only work around I know for this is to use `target_text` and `target_url` instead of `target` in your notifications

**Comment by texnic** [comment]
Hi @audiolion, we speak different languages :) I don't know Django on the level sufficient to understand your post :) Can you elaborate please? Is the code you published a workaround for the issue I reported? Can I use it? If yes, then how?

**Comment by jjkester** [comment]
Sadly, @audiolion s post has disappeared - I have no idea what he wrote here.

I have investigated your issue, and it seems that this seems to be a "feature" of Django's GenericRelation, used by the AuditlogHistoryField (as documented [here](https://docs.djangoproject.com/en/1.10/ref/contrib/contenttypes/)).

I have no idea how to fix this since there seems no way to disable this via any public Django API. I recommend you - for now - to not use AuditlogHistoryField while I/we think of a solution.

**Comment by audiolion** [comment]
What I wrote was an incorrect solution so I removed it, apologies for any confusion.

Relevant bit from the docs @jjkester mentioned:

> Note also, that if you delete an object that has a GenericRelation, any objects which have a GenericForeignKey pointing at it will be deleted as well. In the example above, this means that if a Bookmark object were deleted, any TaggedItem objects pointing at it would be deleted at the same time.
> 
> Unlike ForeignKey, GenericForeignKey does not accept an on_delete argument to customize this behavior; if desired, you can avoid the cascade-deletion simply by not using GenericRelation, and alternate behavior can be provided via the pre_delete signal.

Potentially we could write a `pre_delete` signal that as mentioned above that writes the current history to a new model we create representing deleted history items? I could draft up a PR if you think that is a sane way to do it.

**Comment by jjkester** [comment]
Maybe removing the reference to the model using the `pre_delete` signal would work (just unsetting the `object_id` and `object_pk`). Only thing that remains is coupling all the log entries back together, which may not be that straightforward. Any proposal, whether in text or PR, is of course welcome.

**Comment by audiolion** [comment]
Hm, good idea, if we can do it correctly it would minimize modifications to other parts of the code base that don't need to know if an entry was deleted but display the history all the same. I will play around and see if I can get that working
