### ISSUE TITLE
django-auditlog vs. django-audit-log

### ISSUE THREAD

**Issue by texnic** [jjkester/django-auditlog#109]
I couldn't find this information anywhere. What is the difference between these two projects, having not only very similar names but AFAICT also a very similar purpose? Would be good to have a short clarification here, for the undecided. 

[django-auditlog](https://github.com/jjkester/django-auditlog) (this repo)
[django-audit-log](https://github.com/Atomidata/django-audit-log)

**Comment by jjkester** [comment]
First of all, I do not know the other library by heart. However, I will try to explain my view of things, which of course is very biased towards this project :wink:.

While quickly looking over the code I think the biggest difference is that django-audit-log keeps a shadow table with the log entries. This provides a lot of overhead. This library tries to minimize this by keeping all log entries of all your models in a single table. This makes the library also very predictable. It does not have a lot of code, any somewhat capable Python/Django programmer should be able to figure out exactly what this library does internally within a reasonable amount of time. To be completely honest some later additions to the code are less "clean", the newer functionality tends to take some more code, but the base functionality should be very clear to figure out.

Another difference is that django-audit-log seems to use custom managers to keep log entries. Our approach is different - we only use middleware for automatic logging and give you the freedom to decide what exactly you want to log. Again some honesty: manual logging is not as convenient at the moment as I would like to have it, but that is something we can work on.

Lastly it seems that this library has more active development than the other one.

Are there any specific questions you have, I am happy to answer them.

**Comment by texnic** [comment]
Thanks for this explanation. The reason I've asked is that django-audit-log was created earlier (6 Apr 2011), and the name is so similar that I thought it somehow inspired the creator of this package. But there should also have been something that wasn't so good there, calling for a new solution. Since it's mentioned nowhere, I decided to ask.
