### ISSUE TITLE
field.rel deprecation warning

### ISSUE THREAD

**Issue by chris-griffin** [jjkester/django-auditlog#116]
We need to use `field.remote_field` instead of `field.rel` which is available in django=>1.9. @jjkester are you ok with dropping support for django 1.8? 

The relevant warning:
```py
if getattr(field, 'rel', None) is not None and field.rel.to == LogEntry:
/auditlog/diff.py:25: RemovedInDjango20Warning: Usage of field.rel has been deprecated. Use field.remote_field instead.
```

**Comment by audiolion** [comment]
Django 1.8 is in LTS until at least april 2018 and should remain supported here until that time

**Comment by chris-griffin** [comment]
Ah thanks I misread the release page. I'll submit a PR that is compatible with 1.8 then
