### ISSUE TITLE
eliminate None->blank changes

### ISSUE THREAD

**Issue by agfunder** [jjkester/django-auditlog#121]
Eliminating spurious changes of saving empty fields turning NULL into blank string.  See https://code.djangoproject.com/ticket/9590 for more about this issue.

Included in https://github.com/jjkester/django-auditlog/pull/118

**Comment by agfunder** [comment]
Revised, see: https://github.com/jjkester/django-auditlog/pull/124

**Comment by audiolion** [comment]
IMO if you have set to allow null strings and blank strings and then save a blank string where what used to be a null string, auditlog is working as intended.
