### ISSUE TITLE
object update does not work for models which have many-to-many fields

### ISSUE THREAD

**Issue by shubham-UL** [jjkester/django-auditlog#125]
```python
class MaintenanceSchedules(models.Model):
    description = models.CharField(max_length=256, verbose_name='Description')
    status = models.CharField(max_length=32, verbose_name='Status')
    datacenter = models.ForeignKey(Datacenter)
    impacted_customer = models.ManyToManyField(Organization)
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.description


from auditlog.registry import auditlog

auditlog.register(MaintenanceSchedules)
auditlog.register(MaintenanceSchedules, exclude_fields=['impacted_customer'])
auditlog.register(MaintenanceSchedules.impacted_customer.through)

```

I am trying to log add,update,delete operations for this model.Add and delete operations are getting logged just fine but updation of any field does not register logs.This is only happening with models which have many-to-many relation ,I tried with different options of auditlog.register but nothing works.
Please let me know if this feature is supported or am i missing something.

Python 2.7.9
Django (1.10.3)
django-auditlog (0.4.3)

**Comment by shubham-UL** [comment]
It does not reach log_update method in receivers.py as I tried printing diff ,object does change in the DB.

**Comment by shubham-UL** [comment]
Guys , I wanted to use this library in production but this bug is the showstopper ,can somebody please let me know an estimate when this can be resolved?Let me know if you want more information from my side.
Thanks.

**Comment by agfunder** [comment]
To be clear, you have tried each of these separately, and they all fail?  (Not all together, right?)
```
auditlog.register(MaintenanceSchedules)
auditlog.register(MaintenanceSchedules, exclude_fields=['impacted_customer'])
auditlog.register(MaintenanceSchedules.impacted_customer.through)
```

**Comment by shubham-UL** [comment]
Yes.
I have tried all of them separately.

**Comment by agfunder** [comment]
Can you confirm:
- are you using any other signals in your own code?
- are you using latest version of auditlog?

**Comment by shubham-UL** [comment]
Yes.
After saving i refresh the views.Sender is a different model which is referenced in MaintenanceSchedules.
@receiver(post_save, sender='Datacenter')
def refreshviews():
    xyz()

I tried commenting it out but it still does not work.
I have the same receiver for other models(which dont have mtm relationship) and it works fine.

I am also overriding save() of Organization model ,will it cause any problem?

**Comment by agfunder** [comment]
`I am also overriding save() of Organization model` this is interesting, can you try commenting out your save() and see if it works then @shubham-UL ?
Because in my scenario, I have no trouble with models having m2m.  So I want to know, what is different in your case.

**Comment by audiolion** [comment]
To be able to debug I would need a working example of it or a way to recreate it, is it possible for you to make a small reproducible example of this bug @shubham-UL ? I'd hate for this to be a showstopper for you and want to help you resolve

**Comment by psorab-ul** [comment]
@audiolion Create a separate app in a project with the following code to reproduce the issue : 

> models.py

```
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Datacenter(models.Model):
    name = models.CharField(max_length=128, default='SF', unique=True)

    def __unicode__(self):
        return u'%s' % self.name


class Organization(models.Model):
    name = models.CharField(max_length=128, default='ORG', unique=True)

    def __unicode__(self):
        return u'%s' % self.name


class MaintenanceSchedules(models.Model):
    description = models.CharField(max_length=256, verbose_name='Description')
    status = models.CharField(max_length=32, verbose_name='Status')
    datacenter = models.ForeignKey(Datacenter)
    impacted_customer = models.ManyToManyField(Organization)
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.description

from auditlog.registry import auditlog
auditlog.register(MaintenanceSchedules)
auditlog.register(MaintenanceSchedules.impacted_customer.through)
```

> admin.py
```
from django.contrib import admin
from .models import *

admin.site.register(Datacenter)
admin.site.register(Organization)
admin.site.register(MaintenanceSchedules)
```

> settings.py
```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_name',
    'auditlog'
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'DB_NAME',
        'USER': 'USERNAME',
        'PASSWORD': 'PWD',
        'HOST': '',  # Set to empty string for localhost.
        'PORT': '',  # Set to empty string for default.
    }
}
```

`python manage.py makemigrations`
`python manage.py migrate`
`python manage.py createsuperuser `
`python manage.py runserver`

Log in into django admin console Ex :http://127.0.0.1:8000/admin/ and create **Maintenance Schedule**

It creates audit log entry without `impacted_customer` field which has m2m relationship with Organization : 
```
{"status": ["None", "example"], "datacenter": ["None", "SF"], "description": ["None", "example"], "end_date": ["None", "2017-06-14 12:00:00"], "created_at": ["None", "2017-06-29 14:04:12.216240"], "updated_at": ["None", "2017-06-29 14:04:12.216254"], "id": ["None", "1"], "start_date": ["None", "2017-06-13 06:00:00"]}
```
cc @shubham-UL 

@agfunder commenting out `save()` method did not work.

**Note : Please check the above example in **Django>=1.10**

**Comment by audiolion** [comment]
Hey @psorab-ul as noted in the docs, ManyToMany relationships are not officially supported by this library. However, by doing the `MaintenanceSchedules.impacted_customer.through)` registration, `auditlog` should track those changes. Are you sure you are querying the logs in the right way?

```python
obj = MaintenanceSchedule.objects.first()
impacted_customer_history = LogEntry.objects.get_for_objects(obj.impacted_customer.all())
full_history = (obj.history.all() | impacted_customer_history.all()).order_by('-timestamp')
```
