### ISSUE TITLE
conflict logging in conjunction with django-concurrency

### ISSUE THREAD

**Issue by agfunder** [jjkester/django-auditlog#128]
We extended our fork of django-auditlog at https://github.com/agfunder/django-auditlog/tree/conflicts_m2m with Conflict logging for use in conjunction with django-concurrency.  I mention it here to determine if there is interest in this feature.  This feature would depend on both django-concurrency and django-auditlog.  Another option may be for me to release this as a separate package, but it currently requires changes to django-auditlog internals.

The idea is, django-concurrency provides conflict detection:  two users save the same model, one may overwrite the last user's changes without knowing.  In case of conflict, an exception is raised, which protects from overwrite, but the last version to save will be lost.

I realized that django-auditlog, the LogEntry model could be a good fit for showing the difference between the previous and conflicting versions.  I called it a Conflict action, it is almost like a Change action, but the change failed.

When a user saves a record, and there is a conflict, they are redirected to the django-auditlog screen showing exactly what the conflict was, what each user's changes were, and the user could then reconcile.  With complete logging from django-auditlog, the user's attempted edits are safely saved for reference.  For some applications, some edits take a lot of time and effort which we dont want thrown away due to a conflict.

![conflict](https://user-images.githubusercontent.com/14253857/27811360-59003946-601a-11e7-9839-13b83bde61ea.png)

This screenshot shows what the user sees after they attempt a conflicting save.  This also shows m2m diffing.  Color codings are used to show the differing m2m values on both sides, and common ones are grey.  I blurred to protect our data.

If there is not interest, I will maintain my fork, because I think this feature is very valuable.  In that case, I also wonder if there is a way to allow extensions on top of django-auditlog (ie, without requiring forks).  For example, I have now added two Actions:  MOVE (for tracking movement of mptt nodes showing change of parent), and CONFLICT (this case).  If there were a way to extend django-auditlog, I could maybe add this functionality without modifying the package itself.

(This shot also shows we render the JSON in additional_data as tables.  m2m_changes json is automatically inserted by the m2m tracking code.)

**Comment by audiolion** [comment]
Discussed auditlog extension to supprt this in other topic
