### ISSUE TITLE
The auditlogflush command does not work

### ISSUE THREAD

**Issue by kairatomurbek2** [jjkester/django-auditlog#129]
Hi, Unknown command: 'auditlogflush'
Type 'manage.py help' for usage.

**Comment by audiolion** [comment]
woops! looks like the directory wasn't included when it was packaged up

https://github.com/jjkester/django-auditlog/blob/master/setup.py#L6

**Comment by kairatomurbek2** [comment]
@audiolion And when will you update?

**Comment by audiolion** [comment]
I am not the package owner, so I cannot update, when the PR I submitted is merged and a new release is cut is when it will be available. In the meantime you could just copy the management directory into your own directory if you just need to one-off run the command, you could also install from github with the `pip install -e git://github.com/jjkester/django-auditlog.git#egg=django-auditlog`

**Comment by kairatomurbek2** [comment]
@audiolion  Thanks!
