### ISSUE TITLE
Cascade delete

### ISSUE THREAD

**Issue by AnLeader** [jjkester/django-auditlog#13]
class A(models.Model):
    	...
    
    class B(models.Model):
    	a = models.ForeignKey('A')
    
    class C(models.Model):
    	b = models.ForeignKey('B')
    
    def log_delete(sender, instance, **kwargs):
    	logging
    
    auditlog.register(A)
    auditlog.register(C)

When you delete an instance of A cascade delete occurs removing B and C instances. How can I disable signal for child instances on cascade delete by django?

**Comment by farridav** [comment]
Is this issue caused by django-auditlog or are you referring to djangos default behaviour, if it is the latter you can set the `on_delete` property on model `A` to `SET_NULL`, see [Django docs](https://docs.djangoproject.com/en/1.7/ref/models/fields/#django.db.models.ForeignKey.on_delete)

**Comment by jjkester** [comment]
This is indeed Django's default behaviour. Remember to add ```blank=True, null=True``` to the field definition when you set ```on_delete=SET_NULL```.
