### ISSUE TITLE
How show log in template?

### ISSUE THREAD

**Issue by johndiego** [jjkester/django-auditlog#133]
<b>Hi guys, how i can show template log ?

```
<div class="ui tab animated fadeIn" data-tab="historico">
   {{object.history}}
</div>  
```

**Comment by audiolion** [comment]
`history` is the object that contains the logs, so you could do `object.history.all()` to get all the log entries.

For each log you can iterate through the `changes_dict` property to get the model fields that were modified.

```
        {% for log in event.history.all %}
            {% with actor=log.actor timestamp=log.timestamp|date:"N j, Y \a\t f a" %}
            <tr style="font-weight: bold; background-color: #ddd"><td colspan="3">Modified on {{ timestamp }} by {{ actor }}</td></tr>
            {% for key, value in log.changes_dict.iteritems %}
              <tr>
                <td>{{ key }}</td>
                <td>{{ value.0|default:"Empty Field" }}</td>
                <td>{{ value.1|default:"Empty Field"|striptags }}</td>
              </tr>
            {% empty %}
              <p>No history for this item has been logged yet.</p>
            {% endfor %}
            {% endwith %}
          {% endfor %}
```

**Comment by johndiego** [comment]
Don't show value and field ? just copy past in your code, thanks !
![captura de tela20170803191414](https://user-images.githubusercontent.com/18476845/28946196-2b0f91b6-7899-11e7-9ac8-3fb8e1615d08.png)

**Comment by audiolion** [comment]
Was that a question or comment? 🤔

**Comment by johndiego** [comment]
Question!

**Comment by audiolion** [comment]
if it is saying no history then there is nothing saved in the `changes_dict`, try inspecting it with your debugger or in `python manage.py shell` try 
```python
log = YourModel.history.all()[0]
log.changes_dict
```

and see if there is anything in there
