### ISSUE TITLE
Field verbose_name in log

### ISSUE THREAD

**Issue by aulemasa** [jjkester/django-auditlog#135]
Hello
It is possibile to show field verbose_name in log?

**Comment by johndiego** [comment]
you can get history with verbose_name
![deepinscreenshot_select-area_20170823231935](https://user-images.githubusercontent.com/18476845/29646398-a9862d82-8859-11e7-9fcf-e453296d475d.png)

**Comment by audiolion** [comment]
this is a change I started working on but never finished implementing, basically a way to map field names for when they are displayed to provide a better human readable version, so I guess not until I finish that up

**Comment by aulemasa** [comment]
Ok. Thank you both for response

**Comment by audiolion** [comment]
ok #94 is complete now so when it gets merged you should be able to provide a human readable string mapping for fields

**Comment by aulemasa** [comment]
ok thank you very much :)

**Comment by audiolion** [comment]
Ok @aulemasa by default if you use the `changes_display_dict` property on the `LogEntry` model it will use the `verbose_name` field after the PR goes through and a new release is made.

Gonna close this now
