### ISSUE TITLE
How can I see an object history?

### ISSUE THREAD

**Issue by texnic** [jjkester/django-auditlog#138]
I am using django-auditlog, and I have a nice table in my project's admin site at /admin/auditlog/logentry/. So history tracking works. I have two questions:

1) How can I retrieve an object history programmatically?
2) I register all models with `auditlog.register(<model_name>)` and also—though not always—by adding a field `history = AuditlogHistoryField()`. What is the purpose of the latter? It seems to have no effect on the admin page: models with and without this field seem to be logged.

Thanks!

**Comment by audiolion** [comment]
history puts a generic relation on the instance so you can access it.

e.g.
```
user = User.objects.get(pk=1)
history = user.history.all()
latest_log = user.history.latest()
```
