### ISSUE TITLE
Custom return classes does not display objects in logentry table 

### ISSUE THREAD

**Issue by DylienneKTV** [jjkester/django-auditlog#139]
I am having a problem with the audit log for classes that have a customised return. For example I have this code: 

```
          class Adress(models.Model):
            type_id= models.ForeignKey(AddressType)
            street = models.CharField(max_length=256, null=True)
            number = models.CharField(max_length=16, null=True)
            zip_code= models.CharField(max_length=16, null=True)
            city = models.CharField(max_length=64, null=True)
            country = models.CharField(max_length=64, null=True)

          def __str__(self):
             return self.city

          auditlog.register(Adress)
```

My database records everything nicely, however, the object that changed is not logged because I have a custom return. 

See printscreen example subnets and networks:

<img width="1086" alt="screen shot 2017-09-11 at 11 36 30" src="https://user-images.githubusercontent.com/26649530/30268284-90166e80-96e5-11e7-8e7a-7658e978658c.png">

If I remove the returns I get the object notation properly. But I have a lot of forms where the foreign key needs to be displayed the return I give it, for example "city" for class address. But if I change something with that class, it only returns the city in the table where I would like to see "Address Object". 

Hope you can help me out! 

Best,
Dylienne

**Comment by DylienneKTV** [comment]
Hi, 

What I mean is that as an example, I have a class address, with a custom return “city”. Instead of city, it should return “address object”. As noted in my post, the screenshot is merely an example of how my database looks like. The ip addresses are returned instead of a “… object”. 

Except for subnet, I have no return of the class in the model, then, I can see “subnet object” in de column of the database. 

I hope it is clearer now, if I can aid with some information let me know. 

Best,

**Comment by audiolion** [comment]
The `__str__` method is a contract for the string representation of that model object. If you want it to say `Address object: New York City` then make your `__str__` method

```python

def __str__():
    return "Address object: {}".format(self.city)
```

django-auditlog is grabbing the object representation, aka the contract you defined, if you don't like that contract then change your string representation of your object. `object_repr` is a char field that holds the string representation as defined by you, nothing more.

**Comment by DylienneKTV** [comment]
Hello Audiolion, 

I understand, thank you. 

However, the returns are very much alike as all are ipv4 addresses. I would like to make a distinction between subnets, networks, ip's, pub.ip's etc. In the logentry column, they all return ipv4 notations where it then is not to be distinguished at what object the object_repr belongs to. 

Your solution is okay for this project. 
Thank you. 

Best,

**Comment by audiolion** [comment]
You can write your own `get_additional_data` method to return additional information about the object in a json format that will be tracked by auditlog

https://github.com/jjkester/django-auditlog/blob/v0.4.3/src/auditlog_tests/models.py#L87
