### ISSUE TITLE
LogEntryAdminMixin doesn't support custom primary key. 

### ISSUE THREAD

**Issue by pnhegde** [jjkester/django-auditlog#140]
`link = urlresolvers.reverse(viewname, args=[obj.actor.id])` actor.id is hardcoded. My primary key name is `slug` and not `id`. I ended up creating my custom admin and mixin. It's better to use generic primary key instead of using `id` field.

**Comment by audiolion** [comment]
This is a fairly special case, in general, even if you want to use a different primary key for your models for public exposure, you should still keep a dummy auto id field on the model for indexing purposes for the database to make faster queries.

We can certainly use Django's `model._meta` options to determine the primary key on the model and fix this issue. Could you provide me an example model that you are using that breaks it to test with?

**Comment by audiolion** [comment]
ping @pnhegde

**Comment by pnhegde** [comment]
@audiolion  Many people [recommend](http://postgres-bits.herokuapp.com/#54) UUID as PK in Postgres although it is quite [debatable](https://news.ycombinator.com/item?id=5310280).  
A sample model could be anything where you have UUID as PK.    

```
class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, blank=True, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

```

**Comment by audiolion** [comment]
ah I think I understand now, typically where an alternate primary key is used I see the design pattern of leaving the auto-incrementing dummy id and hiding it while exposing the public uuid/slug/etc. field. So simply referencing `obj.pk` instead of `obj.id` should fix this
