### ISSUE TITLE
audit-log-0.7.0 error in django-1.11.1

### ISSUE THREAD

**Issue by ra00f** [jjkester/django-auditlog#142]
Hi,

Just installed django-audit-log-0.7.0 in my django-1.11.1 (running under python 3.5.2)

makemigration & migrate commands run without any issue. However, when I issue runserver, I get the same error mentioned at [_auditlog error in django 1.10_ #63]([url](https://github.com/jjkester/django-auditlog/issues/63))

```
  self.load_middleware()
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters
```
Any fixes? Thanks.

**Comment by audiolion** [comment]
Wrong library, this library is `pip install django-auditlog` and its highest version is `django-auditlog==0.4.3`
