### ISSUE TITLE
Unknown command: 'auditlogflush'

### ISSUE THREAD

**Issue by Northshoot** [jjkester/django-auditlog#149]
hey,

Great stuff here! I am using I am using 1.11.7 and the command is not found neither it shows up in the help section.

I assumed usage is

`python manage.py auditlogflush`

**Comment by audiolion** [comment]
This is because previous releases excluded the management commands code, and a new release has not been cut since this was updated.

@jjkester perhaps we can do a release to address some of these issues?

**Comment by jjkester** [comment]
We definitely should - I had already planned to do this but it totally slipped my mind. I can promise you that I will do it tomorrow.

**Comment by jjkester** [comment]
Sorry for being a day late, but a new release has just been pushed to pypi. I'm closing this issue as it will most likely be solved - if you run into something please create a new issue for it.
