### ISSUE TITLE
Adding user for automated scripts

### ISSUE THREAD

**Issue by Northshoot** [jjkester/django-auditlog#151]
Hey,

I am doing some automated database maintenance where objects are created, edited, deleted by a script. When the script is executed it shows _system_  as a user. Since I have several independent scripts, I would like to give them a "name" so I can sort and work with auditing logs better rather than just be stuck with a _system._  as a generic term. 

What would be the approach to do it that?

**Comment by agfunder** [comment]
My approach to this is to always store the name of the calling program in the "additional_data" field using get_additional_data().  However that does not allow search/filter through the admin interface but its enough for my needs.

I do it like this:

def get_exec_context():
    import sys
    env={}
    if len(sys.argv)>0:
        env['prog']=sys.argv[0]
    if len(sys.argv)>1:
        env['param1']=sys.argv[1]
    if len(sys.argv)>1:
        env['param_rest']=" ".join(sys.argv[2:])
    return env


class AuditedClass:

    # additional auditlog data
    def get_additional_data(self):
        ....
        return {'exec': get_exec_context(),'uuids':...  }

**Comment by Northshoot** [comment]
Awesome, that is an elegant soliution.

**Comment by agfunder** [comment]
@Northshoot if satisfied would you close this issue?  Thanks!
