### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by eriktelepovsky** [jjkester/django-auditlog#157]
Hi. First of all, thank you very much for your library. It is definitely the best one I've seen and tried across all possible solutions. I have successfully installed it and configured for my models, but I am wondering how to use ``AuditlogHistoryField()`` for the inherited models? I registered both Parent and Child model for auditlog, but the history field is accessible only for the parent instance. Any help is appreciated.

**Comment by audiolion** [comment]
could you post a sample of your code?

**Comment by eriktelepovsky** [comment]
My mistake, sorry. I was missing ``model`` attribute in the DetailView of the inherited model. Now it works perfectly. You can close/delete this issue.
