### ISSUE TITLE
Dateutil requirement tweak

### ISSUE THREAD

**Issue by emorozov** [jjkester/django-auditlog#162]
I suggest modifying dateutil requirement line:
`python-dateutil>=2.6.0,<2.7`

Not a big deal, but it's annoying when there're multiple packages in the requirements with strictly defined conflicting versions.

**Comment by j-wil** [comment]
I second this. I am currently running into a requirements conflict.

`django-auditlog 0.4.5 has requirement python-dateutil==2.6.0, but you'll have python-dateutil 2.6.1 which is incompatible.`

I require python-dateutil==2.6.1 for another requirment.

**Comment by charleswhchan** [comment]
I put together a fix in PR 184. Can someone take a look? Thanks!
