### ISSUE TITLE
Admin interface not properly showing items

### ISSUE THREAD

**Issue by kuipumu** [jjkester/django-auditlog#168]
Hi, why do the admin table show items this way?

![sin titulo](https://user-images.githubusercontent.com/8495728/36941234-e182e2ba-1f2c-11e8-97fa-029026b022d2.png)
![sin titulo](https://user-images.githubusercontent.com/8495728/36941242-2db73ea6-1f2d-11e8-9813-4e1df62dcf88.png)

I copied the app to my local proyect and edited the view to mark_safe this strings to properly show, but, that's not really a good solution, what cain I do?, im using django 2.0.2.

**Comment by audiolion** [comment]
I believe a new release should fix this, we merged a PR recently https://github.com/jjkester/django-auditlog/pull/167 but we haven't done a new PyPI release. @jjkester do you think we could do another minor release?

**Comment by jjkester** [comment]
@kuipumu Can you verify the current repository version works for you?

You can install the current version by running the command below:

```bash
pip install --upgrade git+https://github.com/jjkester/django-auditlog.git@master
```

To go back to the distributed version you can simply uninstall `django-auditlog`, and then reinstall it by just providing the name instead of the repository.

**Comment by kuipumu** [comment]
I upgraded from the current repository and im still getting the same result. I don't know if there is some kind of cache in python, but it's the same. The only way it works is by that workaround I made.

**Comment by audiolion** [comment]
Ahh.. I think the issue is that `mark_safe` wasn't applied after the `format_html`,

Try to edit `mixins.py` file and change `LogEntryAdminMixin` class to have `mark_safe(format_html(...))` and let me know if the urls appear properly

**Comment by kuipumu** [comment]
@audiolion Yes, that was the problem, just has the fix that was pulled to the master branch, @jjkester that upgrade from the master branch worked, the problem was that I was in the wrong virtualenv. Thanks.

**Comment by jjkester** [comment]
I will push a release with the fixes soon, hopefully this week, then it would be safer to go back to the packaged version of auditlog.
