### ISSUE TITLE
User group assignments are not logged

### ISSUE THREAD

**Issue by fuatu** [jjkester/django-auditlog#177]
Hello,

I added the user model to be auditlogged.
When I make changes in the user I see them in audit log. 
However there is a problem with the group assignments. When I change the user adding or removing grousp from it there is no auditlog.

Can you please help with it? 

Regards,
Fuat

**Comment by eriktelepovsky** [comment]
Hi @audiolion 

do you plan to make any enhancements of m2m changes tracking in the near future, please?

**Comment by audiolion** [comment]
@eriktelepovsky not at this time, I only help maintain this library (PRs, issues, and asking for releases to be made). I no longer actively use it and don't need the feature myself so no real skin in the game for me
