### ISSUE TITLE
Use Django 1.7+ migrations

### ISSUE THREAD

**Issue by jjkester** [jjkester/django-auditlog#18]
This will cause issues with Django 1.5 and 1.6 which are currently supported. No South migrations will be provided.

**Comment by mfogel** [comment]
FYI it looks like setup.py isn't installing the migrations when this package is pip installed. One way to get them to show up is to add them like this https://github.com/mfogel/django-simple-email-confirmation/blob/develop/setup.py#L34

**Comment by jjkester** [comment]
Thanks for the heads-up, I'll keep this in mind. This functionality is not finished (as is the whole package), all very much alpha/beta, so it will be fixed later on.

**Comment by jjkester** [comment]
Migrations have been added, issue as observed by @mfogel has been fixed in #15.
