### ISSUE TITLE
Stored XSS in Django Admin

### ISSUE THREAD

**Issue by aaronweaver** [jjkester/django-auditlog#189]
The current version has XSS in Django admin and that was [fixed](https://github.com/jjkester/django-auditlog/blob/master/src/auditlog/mixins.py) on March 1. Can you cut a new release?

Thanks!

**Comment by audiolion** [comment]
We are in the process of cutting a new release right now, the library maintainer is currently traveling. We are working on a process to automate new releases so we can iterate faster.

**Comment by aaronweaver** [comment]
@audiolion any chance you can cut the release this weekend?

**Comment by jihoon796** [comment]
@audiolion - this would be really useful for me as well. Let me know if there's anything I can do to help!

**Comment by PabloCastellano** [comment]
0.4.8 has been released recently and should fix this issue. However it is not available on pypi

**Comment by valentijnscholten** [comment]
@jjkester any chance of a fixed release for pip?

**Comment by jjkester** [comment]
A new release including fixes for Django 3.0 is coming.
