### ISSUE TITLE
This worked - at first...

### ISSUE THREAD

**Issue by ursomniac** [jjkester/django-auditlog#198]
So I installed this and added it to a model.
All the initial tests worked GREAT.

Then I set up an UpdateView on the same model (the view requires login).
Now I can change model records over and over and over again...

... NO logging.

So, does this ONLY work if you make changes FROM the admin but NOT if you make changes OUTSIDE of the Admin?

That would be far less useful.

**Comment by audiolion** [comment]
can you post your code, environment, python version, and django version

**Comment by ursomniac** [comment]
I think I understand better now.
