### ISSUE TITLE
Upload release 0.4.8 to pypi

### ISSUE THREAD

**Issue by PabloCastellano** [jjkester/django-auditlog#226]
Dear author/maintainer.

I've seen that you have recently tagged a new version of django-auditlog.

Unfortunately this release is still not available in pypi. Could you please upload it?

Thanks in advance!

**Comment by PabloCastellano** [comment]
Ping @jjkester

**Comment by valentijnscholten** [comment]
This would fix #189 according to the comments there (no reference to commits)

**Comment by jjkester** [comment]
Hi,

Sorry to keep you all waiting. I'm really busy and have to prioritize time (which means that django-auditlog doesn't get the attention it deserves). I had appointed a couple of contributors, but they also could not find sufficient amounts of time.

I have a couple of days off, I will try to do a large release fixing the largest issues. It is coming.

If anyone is interested in helping me maintain the library, please let me know!
