### ISSUE TITLE
Django 3.0 BUG-FIX six

### ISSUE THREAD

**Issue by ZandorSabino** [jjkester/django-auditlog#235]
no arquivo: 

venvX\Lib\site-packages\auditlog\models.py

**before** 
```
from django.utils.encoding import python_2_unicode_compatible, smart_text
from django.utils.six import iteritems, integer_types

```

**after**
```
from django.utils.encoding import smart_text
from six import iteritems, integer_types, python_2_unicode_compatible
```

https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

**Comment by hckwak** [comment]
@jjkester  When will it be updated??

**Comment by jjkester** [comment]
Django 3 support is coming, see #256 , #257
