### ISSUE TITLE
Accessing actor field in auditlog for list view (of an actor's history)

### ISSUE THREAD

**Issue by qqchdelouis** [jjkester/django-auditlog#248]
Hi, Thank you for this module. It is exactly what I was looking for. I have installed it on my Django Web app, and I can see the data flow through into Admin. What I'm trying now to do is create a simple list view to give Users a list of their recent edit history. How do I access the User/Actor field from the Model instance ?

`class MyModel(models.Model):`
`    ...` 
`    history = AuditLogHistoryField()`

Note : I'm not trying to let a User edit the auditlog ; instead, I'm only trying : `(i).` to get a list of a User's edit history and `(ii).` to get the object pk for each item on the list, so that I can provide a hyperlink to the detail view of the MyModel entry that they edited.

I can `._meta.get_fields()`, but only on `MyModel.objects.first().history.latest()` but not on `MyModel.objects.all()`. 

`1/.` Is it possible to access/search for User/Actor field in a query on `MyModel.objects.all()` ? If so, how ?
`2/.` How would I set that query up in a template to iterate over that for the list view ?

Thank you, again.

**Comment by jjkester** [comment]
You can use `LogEntry.objects.get_for_model()` (takes a model class as argument), `LogEntry.objects.get_for_objects()` (takes a queryset as argument)
