### ISSUE TITLE
update to more/most recent django-dateutil

### ISSUE THREAD

**Issue by valentijnscholten** [jjkester/django-auditlog#250]
django-auditlog currently pins `django-dateutil` to version 2.6.0, which was released in 2016.
other dependencies in my project are using `django-dateutil` 2.8.1 which is the most recent.
this leads to "conflicts" or "incomptabilities". Or at least warning during installation. But it does seem to work fine.

is it feasible to just use the newer/newest `django-dateutil` in `django-auditlog`.

**Comment by jjkester** [comment]
Will be addressed in #257

**Comment by valentijnscholten** [comment]
any chance for a release? with the new pip resolver things are breaking down on conflicting (old) library versions.

**Comment by Kingjmk** [comment]
> any chance for a release? with the new pip resolver things are breaking down on conflicting (old) library versions.

it could break builds as the new resolver breaks on some other packages
