### ISSUE TITLE
F() expression & "changes" column

### ISSUE THREAD

**Issue by S-Abhishek** [jjkester/django-auditlog#255]
Hi,

When model field is incremented using F() expression like so,

```
from django.db.models import F

model_object = SomeModel.objects.get(some_column='90293')
model_object.submit_count = F('submit_count') + 1
model_object.save()
```

The auditlog entry for this .save(), shows the entry like this

`{'changes': '{"submit_count": ["8", "F(submit_count) + Value(1)"]}'}`

But i'm not sure of what is the required outcome in this scenario that must be implemented by this package, should it refresh the entry from db for this particular column and show it as "changes" while the rest of them are unchanged?

**Comment by jjkester** [comment]
Auditlog is designed to read the current value. If that is an F-expression, that's obviously not going to work out as you mentioned. But this behavior is expected.

I do not know what kind of workaround there is for this, as Auditlog doesn't operate on DB level.
