### ISSUE TITLE
Problem with threadlocal

### ISSUE THREAD

**Issue by 7wonders** [jjkester/django-auditlog#31]
When doing an ajax request that performs an update I am getting the following:

```
File "/project/venv/lib/python2.7/site-packages/auditlog/middleware.py", line 74, in set_actor
    instance.remote_addr = threading.local().auditlog['remote_addr']
AttributeError: 'thread._local' object has no attribute 'auditlog'
```

Seems that by the time its reached that block the threading.local() is missing auditlog. Changing to use 'instance.remote_addr = threadlocal.auditlog['remote_addr']' seems to fix it up though.

**Comment by jjkester** [comment]
Seems like a logical fix. Could you prepare a pull request for this? I am happy to include your fix, and I will try to release a bug fix release soon after if possible.

**Comment by jjkester** [comment]
Now I think of it, is the remote address logged properly after applying this fix?

**Comment by jjkester** [comment]
Discussion continued in #32.
