### ISSUE TITLE
Selective logging of changes 

### ISSUE THREAD

**Issue by annp89** [jjkester/django-auditlog#36]
Consider a model ```A```.  This model gets updated in the following 2 ways:
(a) Non-user facing interface that constantly creates/updates model ```A``` instances. 
(b) User facing interface where creates/updates to db instances can be done manually(django-admin interface is a good example). 
In my use-case, I only want to track the changes done by a user via the user facing interface.

Would it be possible to check for an optional model instance attribute or an attribute passed with ```save``` as a ```kwargs``` ,e.g., "_skip_logging" if it is set to ```True``` in ```model_instance_diff``` and if  so, return a distinct value like a constant int (-1) or a string "SKIP_LOGGING" . This value can be checked before creating a Log entry ```receivers.py``` and there by making logs so much more useful.

Thoughts, suggestions?

**Comment by jjkester** [comment]
I'll directly write down my thoughts, apologies in advance if the story seems somewhat vague.

I intended the application as "a quick way to do things" and a framework. The supplied middleware is useful to log everything (which is only a single use case). For more fine-grained logging, manual labour is required :wink:, for example by adding some code to views.

In case of the Django admin example this is not easy to do. An attribute would be the same as not registering a model for logging (which is currently possible by the way). So you could simply not register models which are not edited by users directly.

I think that only logging changes explicitly made by users is something many people will want. And this is easy to do by manually creating ```LogEntry``` objects (but this does not include the Django Admin interface).

However, I think there is a nasty hack for the Django Admin interface. In fact, I think it is bad enough to not document it (apart from mentioning it here). Django's Admin interface has it's own logging. It uses a model. So you could write a signal receiver for the ```pre_save``` and ```post_save``` events of the model from Django's own logging and use this to create a ```LogEntry``` instance. Again, I do not think this solution is the right way to go, but it could solve your problem.

On the other end, how bad is it to log changes NOT explicitly made by users? After all, if a ```LogEntry``` instance has an actor linked to it, that user triggered the change. Whether this is correct depends on how you look at the data. And the interpretation of the data can be different for different projects.

So, this what I think of it. Hopefully this brings you a bit closer to figuring this out. Would like to hear your thoughts after reading this!

**Comment by annp89** [comment]
^ thanks for such a detailed response. Makes perfect sense. I gave django-admin as an example but that was misleading coz my actual use case is a web app user interface where users are allowed to make changes, like a settings page.

The problem actually comes down to what you said "And this is easy to do by manually creating LogEntry objects" 
Im currently pointing to a forked version of this repo and calling the function 'model_instance_diff' and manually creating LogEntry objects on a selective basis by hooking onto a post save signal. This is without registering the models. But I wanna upgrade to 0.3.1 (since it has the changes I need and more :) )
With the latest release, 0.3.1, 'model_instance_diff' has a check for 'include_fields' and 'exclude_fields' and I run into issues here https://github.com/jjkester/django-auditlog/blob/master/src/auditlog/diff.py#L87
https://github.com/jjkester/django-auditlog/blob/master/src/auditlog/registry.py#L93
since my model instances dont have those fields and errors out.

What would you suggest be the best way to use  'model_instance_diff'  and create 'LogEntry' instances?

**Comment by jjkester** [comment]
Manually creating log entries currently is a big hassle, and something needs to be done about that. I do have some ideas. I'll add an issue so it can be implemented for version 4. Feel free to contribute your implementation once I described the issue in detail.

**Comment by annp89** [comment]
Awesome!! I'd love to contribute once you have the issue/ desired implementation up.

**Comment by jjkester** [comment]
The issue has been up for some two weeks now. I'll close this one in favor of #37.
