### ISSUE TITLE
how to customize change message for create,update,delete operations?

### ISSUE THREAD

**Issue by shashank9487** [jjkester/django-auditlog#44]
I need to customize change message option after standard actions, because default is not suitable to my requirements. For this i need to modify `changes = model_instance_diff(old, new)`, but still searching how it is possible by overriding.

**Comment by jjkester** [comment]
What do you want to achieve exactly?

**Comment by jjkester** [comment]
Closing this issue since it is becoming quite old. Please open a new issue if you want to continue discussing this topic.
