### ISSUE TITLE
Error codeship

### ISSUE THREAD

**Issue by paulovictor** [jjkester/django-auditlog#46]
CommandError: Conflicting migrations detected (0006_object_pk_index, 0005_auto_20151010_1453 in auditlog).
To fix them run 'python manage.py makemigrations --merge'

I'm taking this error when I try to use the 0.3.2 version in codeship.
Apparently, there is some problem with these migrations.
I'm having to use the 0.3.1 version.
Thank you.

**Comment by jjkester** [comment]
Which version of Django are you using, and what kind of database (PostgreSQL, MySQL, ...)?

**Comment by jjkester** [comment]
Closing this issue since the original poster has not responded.
