### ISSUE TITLE
Index column size too large on MySQL 5.7

### ISSUE THREAD

**Issue by daveyvanniftrik** [jjkester/django-auditlog#54]
`django.db.utils.OperationalError: (1709, 'Index column size too large. The maximum column size is 767 bytes.')`

Can be fixed by setting `max_length=255` in `0006_object_pk_index.py`.

**Comment by jjkester** [comment]
The length in that migration is obviously a typo, it should be 255. I'll look into the best way to fix this, simply changing an older migration is fine for new users, but not for existing users.

**Comment by daveyvanniftrik** [comment]
Great, thanks!

**Comment by WingingTime** [comment]
me too.

django.db.utils.OperationalError: (1709, 'Index column size too large. The maximum column size is 767 bytes.')

**Comment by jjkester** [comment]
The master branch on GitHub currently has a migration which fixes this. You can copy this migration into your local copy or just install the package manually until 0.4.0 has been released (which may take some time without outside help).

**Comment by jjkester** [comment]
I have to correct myself. It seems that the latest 0.3.3 release already contains this fix. However, the 0006 migration still contains the 256 length.

You can try migrating to 0005, fake migrating 0006 and then migrating to 0007.

The next release will contain a fix for this problem (probably changing the old migration).
