### ISSUE TITLE
Add an admin interface

### ISSUE THREAD

**Issue by robguttman** [jjkester/django-auditlog#55]
It would be nice to have a simple admin interface to make it easy for anyone to see, search, and filter the log (e.g., by model name).

**Comment by jjkester** [comment]
Good idea :smiley: 

I do not have a lot of time so I will appreciate it if you submitted a pull request for the admin interface. We can discuss (if needed) some details in the pull request.

**Comment by 029xue** [comment]
That dose necessary to make this app comprehensive.

btw, when a stable release could be expected?

Thanks for the good code.

**Comment by jjkester** [comment]
The admin interface has been added. A stable release is a bit scary considering that I am no longer using this app myself, and development and maintentance is slow. Stable would mean keeping up with changes, committing to how things work now (which might change, I have at the moment not a lot of experience with using the app), et cetera. However, I think you can feel comfortable with using this in a production environment.

**Comment by 029xue** [comment]
I've upgraded to version 0.4.0 see the admin interface added. Thanks for the good work!

BTW, it is possible to integrate the AuditLog logs to default object_history page? it would be charm if the changes detail can be viewed there :)

**Comment by jjkester** [comment]
I think that would be possible with a modified admin, but someone would have to look into it. You can open a new issue for that.
