### ISSUE TITLE
Wrong user is written to audit log

### ISSUE THREAD

**Issue by eugene-daragan-codex** [jjkester/django-auditlog#72]
Found that sometimes a wrong user is written to audit log when there is a high concurrency in access to server. Some investigations shown that the reason of it is `AuditlogMiddleware` imperfections, specifically a multiple signal receiver setup for `LogEntry` pre-save (https://github.com/jjkester/django-auditlog/blob/master/src/auditlog/middleware.py#L46)

A possible chain of events to reproduce the bug:
1.  User `A` does a request to the server, `AuditlogMiddleware` attaches a signal receiver to `LogEntry`,  with `signal_duid`specific to thread that prcesses the request of the user `A`.
2.  User `B` does a request to the server, `AuditlogMiddleware` also attaches a signal receiver to `LogEntry`, with `signal_duid`specific to thread that prcesses the request of the user `B`
3.  Thread that processes request of user `B` does a write to `LogEntry` table, so pre-save signal for `LogEntry` is triggered.
4.  Because two signal handlers are attached to `LogEntry` pre-save at the moment (for user `A` and `B`), they are triggered sequentially, with the first one specific for user `A`, so user `A` is written to `actor` field of `LogEntry` record.
5.  After, signal handler specific to user `B` is triggered, but because of overwrite protection (https://github.com/jjkester/django-auditlog/blob/master/src/auditlog/middleware.py#L77) the user isn't written to the `LogEntry` record, leaving incorrect user `A` in a record for user `B`
6.  After the request of user `B` is processed, its signal handler is removed from `LogEntry` pre-save signal handlers by its specific `signal_duid`, leaving the only signal handler for user `A`, so any `LogEntry` writes for the user will write correct actor.
7.  At the end of user `A` request, its signal handler for `LogEntry` is removed by its `signal_duid`

There are also some thoughts about how to fix it: when currying `set_actor` to request user (https://github.com/jjkester/django-auditlog/blob/master/src/auditlog/middleware.py#L45), we can also curry `signal_duid` stored in `threading.local`, and when actually doing an actor write in `set_actor`, check if passed `signal_duid` matches the current value in `threading.local`. Match would mean that we execute signal handler of corresponding thread, so write the actor value, and avoid any writes on mismatch - because its a signal handler for different thread/user.

**Comment by jjkester** [comment]
Thanks for your issue report! This obviously has to be fixed. Since I'm low on time and this project doesn't have a high priority I encourage you to implement your suggestion yourself and submit a pull request. Either way, your input is appreciated.

**Comment by Isszul** [comment]
This was a problem for us too so I've created a pull request for an implementation of @eugene-daragan-codex s' suggestion

**Comment by jjkester** [comment]
For reference, fixed in #74.

**Comment by jjkester** [comment]
It has taken some time, sadly, but 0.4.1 is out and can be downloaded through pypi or from the 'Releases' part of this web site.
