### ISSUE TITLE
Problems with loading  fixtures

### ISSUE THREAD

**Issue by rrauenza** [jjkester/django-auditlog#8]
I'm having problems with using this and also having fixtures -- seems to come down to a lot of instances where a related object doesn't exist yet.  

I was going to wrap your code with try: ... except ObjectDoesNotExist: ... and submit the code back to you ... but I'm wondering if it would be preferable to just turn off tracking during fixture loading -- and is that even possible?

**Comment by jjkester** [comment]
Discussion continued in #17.
