### ISSUE TITLE
DateTimeFields change if the timezone changes.

### ISSUE THREAD

**Issue by Kurocon** [jjkester/django-auditlog#82]
Hello!

I was trying to implement audits for some models we use, and some of those models use Django DateTimeFields. When I update any field in the model, the auditlog also creates a change entry for the DateTimeField, changing it from timezone UTC to UTC+1, but when Django accesses the model after that, it just gets converted back to UTC time. This makes it so that the DateTimeFields are always marked as changed, even if it is actually the same time. See the image for an example:

![image](https://cloud.githubusercontent.com/assets/1193988/21829108/90448b64-d794-11e6-9d8d-b5e3fe40fb96.png)

**Comment by jjkester** [comment]
Clearly a bug. Comments in the PR (#86).
