### ISSUE TITLE
Model registration decorators

### ISSUE THREAD

**Issue by skorokithakis** [jjkester/django-auditlog#88]
The current syntax is pretty much the poster child for decorators:

~~~.python
class MyModel(models.Model):
    pass
auditlog.register(MyModel, exclude_fields=["example"])
~~~

I propose the following:

~~~.python
@auditlog.register(exclude_fields=["example"])
class MyModel(models.Model):
    pass
~~~

Would you be interested in a PR?

**Comment by jjkester** [comment]
Seems useful. I am actually very interested in a PR, looking forward to your solution.
