### ISSUE TITLE
Release to PyPI

### ISSUE THREAD

**Issue by grantmcconnaughey** [jjkester/django-auditlog#89]
Hi! We are currently being bit by the `User.full_name` issue from #83. I see that that has been fixed in #85 and is in master, however there is not an updated version in PyPI.

Could a new version of django-auditlog please be released to PyPI?

Thanks!

**Comment by jjkester** [comment]
Hi,

Sorry for the late reply. A new release is planned for this week/weekend.

**Comment by jjkester** [comment]
Hi,

I have decided to delay the release a bit to allow contributors to fix some more recently discovered bugs. If I do not receive a pull request before the end of the week I will release a new version nevertheless. Thanks for your patience.
