### ISSUE TITLE
Question: What's the best way to splice in extra information?

### ISSUE THREAD

**Issue by johngoodleaf** [jjkester/django-auditlog#9]
I'd like to record an extra bit of information associated with each change (UPDATE)--the reason for the change, which will be provided by the user.  How can I inject that into an audit record?

**Comment by jjkester** [comment]
I suggest adding an extra optional ```comment``` text field. It can (obviously) not be used when creating automatic log entries, but it should suffice for manual created entries, as described by @johngoodleaf.

**Comment by annp89** [comment]
So, I've had this issue come up. My usecase is as follows: 
Consider object <code>Child</code> with foreign key to object <code>Parent</code>. I wanted to store data(id, name, etc.) of foreign key relationships in the LogEntry instances. So when <code>Child</code>  gets deleted, this allows me to map the LogEntry for deletion to the <code>Parent</code>using the extra information stored and thereby display logs for all actions associated with objects related to <code>Parent</code>.

The way I resolved it in a generic way was by adding a <code>detailed_object_repr = JSONField(blank=True, null=True)</code> in the LogEntry model. In the Manager method for log_create, I check to see if a <code>get_detailed_object_repr()</code> method is defined in my models. If defined, it sets this field with values returned by it, else <code>None</code>.

The naming can be changed to <code>additional_data</code> and <code>get_additional_data</code> to be more flexible as to what goes in there.

I plan to open a pull request against your branch if that works?

**Comment by jjkester** [comment]
You are always free to open a pull request, but I am not (yet) convinced this is the best way to achieve this, although it seems like a minimalist and easy to work with solution (which is a good thing). I encourage you to have a go at it, and I am looking forward to your PR.

**Comment by jjkester** [comment]
This issue will be fixed in #21.
