### ISSUE TITLE
flake8 adherence

### ISSUE THREAD

**Issue by audiolion** [jjkester/django-auditlog#95]
The codebase currently doesn't include formatting or styling standards, do you mind if we use flake8? In general it looks like you have stuck to 120 characters max and the usual flake8 standards, it is just never formally declared.

I can create a new PR for this:

- [ ] add `.flake8` config
- [ ] fix all .flake8 errors or add `noqa` where sensical
- [ ] add flake8 testing to `.travis.yml` builds
- [ ] update documentation about using flake8
- [ ] add flake8 to requirements documentation
- [ ] integrate with coveralls or codecov and add a badge to README

**Comment by jjkester** [comment]
Personally I use a _lot_ of inspections in PyCharm to adhere to coding style, however, making it explicit does not seem like a bad idea (actually, a pretty good idea).

**Comment by skorokithakis** [comment]
My personal plugins, in case it helps:

~~~
flake8
flake8-docstrings
flake8-import-order
flake8-tidy-imports
pep8-naming
~~~

My setup.cfg includes:

~~~
[flake8]
import-order-style = smarkets
~~~

**Comment by lucas03** [comment]
Coala might be a good fit https://github.com/coala/coala
