### ISSUE TITLE
Don't crash when the audited model doesn't have an admin page

### ISSUE THREAD

**Issue by skorokithakis** [jjkester/django-auditlog#99]
Currently, auditlog tries to generate links to the referenced instance sections in the admin, but sometimes the instances aren't enabled in the admin. auditlog should probably catch that exception and not generate a link.

**Comment by jjkester** [comment]
Good catch. Are you willing to write a fix and submit a PR for that?
I'll hold back the next bugfix release just a few days in case you decide to submit a PR soon, otherwise this will have to be included in the next release.

**Comment by skorokithakis** [comment]
I'll see if I can do that quickly, thank you.

**Comment by skorokithakis** [comment]
Submitted, let me know!

**Comment by amiraliakbari** [comment]
If the user model is not enabled in admin, the user_url function will fail similarly. I think the same try-catch fix should be applied to that function too.
